include $(APPDIR)/Make.defs

# Touchscreen test application

PROGNAME = ts_test
PRIORITY = 100
STACKSIZE = 2048
MODULE = $(CONFIG_AIC_TS_TEST)

MAINSRC = aic_ts_test.c

include $(APPDIR)/Application.mk
