obj-y += panel_com.o
obj-y += panel_dbi.o
obj-y += panel_dsi.o

obj-$(CONFIG_AIC_SIMPLE_PANEL) += panel_simple.o
obj-$(CONFIG_AIC_PANEL_DBI_ST7789) += panel_dbi_st7789.o
obj-$(CONFIG_AIC_PANEL_DBI_ILI9341) += panel_dbi_ili9341.o
obj-$(CONFIG_AIC_PANEL_DBI_ILI9488) += panel_dbi_ili9488.o
obj-$(CONFIG_AIC_PANEL_DBI_ST77912) += panel_dbi_st77912.o
obj-$(CONFIG_AIC_PANEL_DBI_ST77916) += panel_dbi_st77916.o
obj-$(CONFIG_AIC_PANEL_DBI_ST77903) += panel_dbi_st77903.o
obj-$(CONFIG_AIC_PANEL_DBI_ILI9327) += panel_dbi_ili9327.o
obj-$(CONFIG_AIC_PANEL_DBI_CO5300) += panel_dbi_co5300.o
obj-$(CONFIG_AIC_PANEL_DBI_ILI9486L) += panel_dbi_ili9486l.o

obj-$(CONFIG_AIC_PANEL_DSI_SIMPLE) += panel_dsi_simple.o
obj-$(CONFIG_AIC_PANEL_DSI_XM91080) += panel_dsi_xm91080.o
obj-$(CONFIG_AIC_PANEL_DSI_ST7797) += panel_dsi_st7797.o
obj-$(CONFIG_AIC_PANEL_DSI_ST7703) += panel_dsi_st7703.o
obj-$(CONFIG_AIC_PANEL_DSI_ILI9881C) += panel_dsi_ili9881c.o
obj-$(CONFIG_AIC_PANEL_DSI_HX8394) += panel_dsi_hx8394.o
obj-$(CONFIG_AIC_PANEL_DSI_JD9365) += panel_dsi_jd9365.o
obj-$(CONFIG_AIC_PANEL_DSI_AXS15231B) += panel_dsi_axs15231b.o
obj-$(CONFIG_AIC_PANEL_DSI_NV3051) += panel_dsi_nv3051.o
obj-$(CONFIG_AIC_PANEL_DSI_FL7707) += panel_dsi_fl7707.o
obj-$(CONFIG_AIC_PANEL_DSI_FT8201) += panel_dsi_ft8201.o
obj-$(CONFIG_AIC_PANEL_DSI_ST7701S) += panel_dsi_st7701s.o
obj-$(CONFIG_AIC_PANEL_DSI_EDP_LT9811EXB) += panel_dsi_edp_lt8911exb.o

obj-$(CONFIG_AIC_PANEL_RGB_ST7701S) += panel_rgb_st7701s.o
obj-$(CONFIG_AIC_PANEL_RGB_GC9A01A) += panel_rgb_gc9a01a.o
obj-$(CONFIG_AIC_PANEL_RGB_NT35560) += panel_rgb_nt35560.o
obj-$(CONFIG_AIC_PANEL_RGB_ST77922) += panel_rgb_st77922.o
obj-$(CONFIG_AIC_PANEL_SRGB_HX8238) += panel_srgb_hx8238.o

obj-$(CONFIG_AIC_PANEL_BRIDGE_LT8911) += panel_edp_lt8911.o
obj-$(CONFIG_AIC_PANEL_LCOS_HX7033) += panel_lcos_hx7033.o
